### ISSUE TITLE
Feature Request: Add support for Generic WiFi Plugs (Tuya-based IoT devices)

### ISSUE THREAD

**Issue by sebkajeka** [devildant/OctoPrint-ShutdownPrinter#2]
There's been a recent breakthrough with open-source support for Tuya IoT devices which lets cheap generic WiFi plugs be controlled programmatically after retrieving an API key from Tuya dev site.

https://github.com/TuyaAPI/link
https://github.com/TuyaAPI/cloud

I would be interested in seeing this added to this plugin as currently I have my printer configured using a setup like this.

**Comment by devildant** [comment]
Hello, 
I first created this plugin so that it interfaces with the plugin "OctoPrint-TPLinkSmartplug".
"OctoPrint Shutdown Printer" aims to send a specific GCODE (M81 with IP) according to certain events / actions. There are many different plugs, and integrating them all into the plugin will make it unstable and heavy.

After all, nothing prevents you from creating an octoprint plugin with a gcode trigger that will detect the gcode code sent by "OctoPrint Shutdown Printer".
