### ISSUE TITLE
Printer doesn't shut down

### ISSUE THREAD

**Issue by modem7** [devildant/OctoPrint-ShutdownPrinter#3]
It seems that the plugin sends the M81 command, but it doesn't send the M81 IP command, so printer just stays there with "printer powered off" (so it's disconnecting)

Current settings
![capture](https://user-images.githubusercontent.com/4349962/41802158-c1cb738c-7676-11e8-8592-7d7493b54361.JPG)

**Comment by devildant** [comment]
could you try to remove IP and re set and save ?

**Comment by modem7** [comment]
Will give it a try!

**Comment by devildant** [comment]
I tried my plugin inside new instance of docker with virtual printer, and after print finish cancel... the plugin send the gcode M81 with IP correctly.

**Comment by vador98** [comment]
It would be nice if this could also work with the tasmota plugin.  I have my printer powered using a sonoff device that can be turned on/off remotely.

**Comment by vador98** [comment]
Ahh- Thank you!

**Comment by mamejay** [comment]
Hello there.  I am trying to get this working.  I have installed your plugin and TPLink plugin as well as the  Tasmota plug in mentioned on the main page.  My adapter does not shut off after print job complete.  I have tried to just issue a M81 192.168.1.112 in the terminal window to see if this will just shutdown but it does not. Am I missing something?  Do I need to configure the Tasmota plug in and if so what details are required?  Thanks

**Comment by devildant** [comment]
Hello,
firstly, "shutdown printer" plugin is only a client that sends the command exteinction to different plugins as tplink.
the Tplink plugin is developed by another person.
however, for Tplink or Tasmota plugins to work, you must first have a corresponding connected plug.
example of taking for tplink: https://www.amazon.fr/gp/product/B01I59FP3E/ref=as_li_ss_tl?ie=UTF8&psc=1&linkCode=ll1&tag=4527896-21&linkId=268be5a3515caf00ea71afd5e09d4bda
so in general it is useless to have both plugins at the same time (tplink or Tasmota)
if you have a connected plug (corresponding to the plugin) and connect to your printer.
you must either enable the GCODE trigger if you are using GCODE mode of  "shutdown printer" , or use the API of the target plugin with the "shutdown printer" API mode
exemple : 
https://plugins.octoprint.org/assets/img/plugins/TPLinkSmartplug/smartplug_editor.png
![image](https://user-images.githubusercontent.com/8700106/42203898-75c6eab6-7ea0-11e8-865f-469f642aa1fd.png)

**Comment by mamejay** [comment]
Perfect.  I did not have the GCODE Trigger enabled in the TPLink plug in.  Thanks for that.  The M81 code works.  Should work on the next print.

**Comment by devildant** [comment]
hello @hwiguna ,
 use mode GCODE with parameter 192.168.254.10
API mode and custom API are only for use with plugins (or other) that does not monitor the GCODE M81.
can you tell me more about your problem?

**Comment by hwiguna** [comment]
I am using TP-Link Smartplug Octoprint plugin with TP-Link WiFi outlet.  I plug in the printer to that outlet.  The Raspberry pi running Octoprint is always powered (not on that switched outlet).  I wonder if the problem is with the TP-link plugin because sometimes when I try to turn it ON, the plugin thinks the outlet is ALREADY on.  

Parameters for tp-link smartplug is included in my previous comment.
I do not know if TP-Link Smartplug monitors GCODE M81 or not :-(

I will try using GCODE with parameter 192.168.254.10 on ShutdownPrinter plugin.  Thank you.

**Comment by devildant** [comment]
Initially I created this plugin to work with tplink, and in your option (tplink plugin), you have activate the GCODE trigger (it's good). by doing this you tell to tplink plugin : monitor the GCODE M81

Otherwise, I made a change to the custom API / API mode, I had some problems with the used REST library (which I changed). so potentially your problem was due to this library
